// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_8_ColinKorsmo.Models;

#nullable disable

namespace lab_8_ColinKorsmo.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20241024141114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("lab_8_ColinKorsmo.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AdmitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymptomDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdmitDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samantha",
                            LastName = "Carter",
                            SymptomDescription = "Severe migraines, Erratic behavior"
                        },
                        new
                        {
                            Id = 2,
                            AdmitDate = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            LastName = "O'Neill",
                            SymptomDescription = "Hallucinations, Memory loss"
                        },
                        new
                        {
                            Id = 3,
                            AdmitDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            LastName = "Jackson",
                            SymptomDescription = "Seizures, Extreme mood swings"
                        },
                        new
                        {
                            Id = 4,
                            AdmitDate = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            LastName = "Hammond",
                            SymptomDescription = "Loss of motor control, Speech difficulties"
                        },
                        new
                        {
                            Id = 5,
                            AdmitDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janet",
                            LastName = "Fraiser",
                            SymptomDescription = "Persistent dizziness, Glows in the dark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
